export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const SET_LOADING = "SET_LOADING";
export const FETCH_CHANNELS = "FETCH_CHANNELS";
export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const SHUTUUUUUUUP = "SHUTUUUUUUUP";
